version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./src:/var/www/html
      - xhprof:/var/www/xhprof
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/xhprof.conf:/etc/nginx/conf.d/xhprof.conf
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
      - xhprof:/var/www/xhprof

volumes:
  xhprof:
